name: synapse-corrector
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - flask>=2.0.0
  - pandas>=1.3.0,<2.0.0
  - numpy>=1.20.0
  - pip
  - pip:
    - Werkzeug>=2.0.0
    - Jinja2>=3.0.0
    - MarkupSafe>=2.0.0
    - itsdangerous>=2.0.0
